export const REQUEST_SHOPS = "REQUEST_SHOPS";
export const RECEIVE_SHOPS = "RECEIVE_SHOPS";
export const REQUEST_LOCATION = "REQUEST_LOCATION";
export const RECEIVE_LOCATION = "RECEIVE_LOCATION";
export const SELECT_STORE = "SELECT_STORE";
